name: barbershop_frontend
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_layout_grid: ^1.0.6
  flutter_screenutil: ^5.3.1
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.0.3

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  assets:
    - .env
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
